name: CI
on:
  push:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Poetry
        run: pip install poetry==1.7

      - name: Install Dependencies
        run: poetry install --with=dev

      - name: Check Lint
        run: make lint-strict

      - name: Check Types
        run: make mypy

      - name: Run Tests
        run: make test

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Try Build
        run: poetry build
