name: CI
on: push


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]
        poetry-version: ["1.3"]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pip install poetry==${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: poetry install --with=dev,docs

      - name: Check Types
        run: make mypy

      - name: Run Tests
        run: make test

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
